import{a as w,S,i as q}from"./assets/vendor-b0d10f48.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))s(t);new MutationObserver(t=>{for(const n of t)if(n.type==="childList")for(const c of n.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&s(c)}).observe(document,{childList:!0,subtree:!0});function o(t){const n={};return t.integrity&&(n.integrity=t.integrity),t.referrerPolicy&&(n.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?n.credentials="include":t.crossOrigin==="anonymous"?n.credentials="omit":n.credentials="same-origin",n}function s(t){if(t.ep)return;t.ep=!0;const n=o(t);fetch(t.href,n)}})();const v="https://pixabay.com/api/",E="44067524-7b37ef940db212c179aad5861";async function u(e,r=1,o=15){try{return(await w.get(v,{params:{key:E,q:e,image_type:"photo",orientation:"horizontal",safesearch:!0,page:r,per_page:o}})).data}catch(s){throw console.error("Error fetching images:",s),new Error("Failed to fetch images")}}const f=document.querySelector(".gallery"),d=document.querySelector(".loader"),m=document.querySelector(".btn");let $=new S(".gallery a",{captionsData:"alt",captionDelay:250});function y(e){const r=e.map(o=>`<li class="gallery-item">
            <a class="gallery-link" href="${o.largeImageURL}">
                <img class="gallery-image" src="${o.webformatURL}" alt="${o.tags}" />
            </a>
            <ul class='info'>
                <li class="info-image"><strong class="info-comment">Likes</strong> ${o.likes}</li>
                <li class="info-image"><strong class="info-comment">Views</strong> ${o.views}</li>
                <li class="info-image"><strong class="info-comment">Comments</strong> ${o.comments}</li>
                <li class="info-image"><strong class="info-comment">Downloads</strong> ${o.downloads}</li>
            </ul>
        </li>`).join("");f.insertAdjacentHTML("beforeend",r)}function a(e){q.error({title:"Error",message:e})}function A(){f.innerHTML=""}function g(){d.style.display="block"}function h(){d.style.display="none"}function p(){m.style.display="block"}function L(){m.style.display="none"}function b(){$.refresh()}function I(){const e=document.querySelectorAll(".gallery-item");if(e.length>0){const r=e[0].getBoundingClientRect().height;window.scrollBy({top:r*2,behavior:"smooth"})}}const P=document.querySelector(".form-search"),O=document.querySelector('.form-search input[name="query"]'),B=document.querySelector(".btn");let l="",i=1;P.addEventListener("submit",D);B.addEventListener("click",H);async function D(e){if(e.preventDefault(),l=O.value.trim(),!l){a("Please enter a search term");return}A(),L(),g(),i=1;try{const r=await u(l,i);r.hits.length===0?a("Sorry, there are no images matching your search query. Please try again!"):(y(r.hits),p(),b())}catch(r){a("An error occurred while fetching images"),console.error(r)}finally{h()}}async function H(){i+=1,g();try{const e=await u(l,i);y(e.hits),i*15>=e.totalHits?(L(),a("We're sorry, but you've reached the end of search results.")):p(),b(),I()}catch(e){a("An error occurred while fetching images"),console.error(e)}finally{h()}}
//# sourceMappingURL=commonHelpers.js.map
